apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo
  namespace: security-team
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-demo
  template:
    metadata:
      labels:
        app: nginx-demo
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: nginx
        image: nginxinc/nginx-unprivileged:latest  
        ports:
        - containerPort: 8080  
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-demo
  namespace: security-team
spec:
  type: LoadBalancer
  ports:
  # External port (ELB listens here)
  - port: 80  
  # Targets container's port
    targetPort: 8080  
  selector:
    app: nginx-demo